name: Docker build action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker login -u $username -p $password
          
      - name: Pre-docker build
        run: |
          docker pull corexchain/corex:latest || true
          docker tag corexchain/corex:latest corexchain/corex:prev

      - name: Build Docker Image
        run: make corex-image 

      - name: Push hub.docker.com
        run: |
          docker tag corex:latest corexchain/corex:latest
          docker push corexchain/corex:latest
          docker push corexchain/corex:prev


